### ISSUE TITLE
Preprocessing images and detectors

### ISSUE THREAD

**Issue by unnat** [594zyc/HiTUT#6]
Hi @594zyc,

This issue is related to and supplements #2 about data preprocessing.

1. I want to preprocess the images in a different way and run detection again. To this end, I would need `data/full_2.1.0_imgs.hdf5`. Is that right?

2. Could you please share the code of obtaining `data/full_2.1.0_imgs.hdf5` from raw images released by the ALFRED authors  [[reference to their code](https://github.com/askforalfred/alfred/blob/23c82fd49cffa52b7ab0a67dc06b467d632711fb/data/download_data.sh#L34)]

3. How do you suggest I modify the visual processing for HiTUT if I wish to use only depth images? Would the receptacles and object detectors need retraining?

To be clear, I need to change only the visual preprocessing, nothing else.

Thanks!

**Comment by 594zyc** [comment]
Hi @unnat,

The hdf5 is nothing more but just a collection of all the RGB images in ALFRED, which should be easy to implement in several lines. The visual processing is very simple and quite limited in HiTUT, where I use a Mask RCNN to convert RGB images to objects represented by its class, confidence score and bounding box coordinates. Only such symbolic representations are fed into the main model. I do not even use dense image features.  I do not suggest following the visual processing procedure in HiTUT. 

For your third question, I am not sure whether there exists any object detection model that can detect objects based on depth image only. Intuitively it is tricky since the important texture and color information is lost. My suggestion is that you may try to use the dense embedding feature of depth images. 

Hope this can help.

**Comment by unnat** [comment]
Thanks, this makes sense. 

Quick followups/clarifications:
1. Do you have pointers on where+what changes does one have to make if they want to use ResNet (dense) features for the visual representation (instead of the symbolic representations mentioned by you)
2. The hdf5 is structured as [task][image_name] as per `img_path_batch = [self.image_data[dp][b] for b in batch]` ([line](https://github.com/594zyc/HiTUT/blob/7c10663e2056e6dc4dcdc943e8f70602c71089d4/data/dataset.py#L669)), right? 
3. One can directly just use `full_2.1.0` released by ALFRED authors for the above hdf5?

**Comment by 594zyc** [comment]
1.  The input sequence of HiTUT is fixed to 128 tokens which consists of ([cls] + [indicator of none object] + [object repr] x 30 + [instruction token] x 64 + [action/subgoal history] x 32). See [here](https://github.com/594zyc/HiTUT/blob/7c10663e2056e6dc4dcdc943e8f70602c71089d4/models/model/mmt.py#L46).  You should replace my object representations (word embedding + coordinates and confidence score) with your object-level resnet feature if you have an object detector, or just use a single resnet feature vector setting arg.topk_objs=0. You also need to modify the input transformation layer [here](https://github.com/594zyc/HiTUT/blob/7c10663e2056e6dc4dcdc943e8f70602c71089d4/models/model/mmt.py#L100). 
2. Yes. 
3. Yes.

**Comment by unnat** [comment]
Sorry for not replying earlier. This provides clear pointers, thank you!
